CREATE SEQUENCE SEQ_CATEGORIA_PRODUTO
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE CATEGORIA_PRODUTO (
    id INTEGER DEFAULT nextval('SEQ_CATEGORIA_PRODUTO'),
    DESCRICAO VARCHAR(60) NOT NULL,

    CONSTRAINT PK_CATEGORIA_PRODUTO PRIMARY KEY (ID)
);
