CREATE SEQUENCE SEQ_ACESSO
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE ACESSO (
    id INTEGER DEFAULT nextval('SEQ_ACESSO'),
    DESCRICAO VARCHAR(60) NOT NULL,

    CONSTRAINT PK_ACESSO PRIMARY KEY (ID)
);
