CREATE SEQUENCE SEQ_PESSOA
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE PESSOA_FISICA (
    ID INTEGER DEFAULT nextval('SEQ_PESSOA'),
    NOME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    DATA_NASCIMENTO DATE,
    
    CONSTRAINT PK_PESSOA_FISICA PRIMARY KEY (ID)
);

CREATE TABLE PESSOA_JURIDICA (
    ID INTEGER DEFAULT nextval('SEQ_PESSOA'),
    NOME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CATEGORIA VARCHAR(60) NOT NULL,
    CNPJ VARCHAR(20) NOT NULL,
    INSC_ESTADUAL VARCHAR(20) NOT NULL,
    INSC_MUNICIPAL VARCHAR(20),
    NOME_FANTASIA VARCHAR(100) NOT NULL,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_PESSOA_JURIDICA PRIMARY KEY (ID)
);
