CREATE SEQUENCE SEQ_ENDERECO
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE ENDERECO (
    ID INTEGER DEFAULT nextval('SEQ_ENDERECO'),
    RUA VARCHAR(100) NOT NULL,
    CEP VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL, 
    
    CONSTRAINT PK_ENDERECO PRIMARY KEY (ID)
);

