ALTER TABLE ENDERECO ADD COLUMN ID_PESSOA_FISICA INTEGER;
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_PESSOA_FISICA FOREIGN KEY (ID_PESSOA_FISICA) REFERENCES PESSOA_FISICA(ID);
ALTER TABLE ENDERECO ADD COLUMN ID_PESSOA_JURIDICA INTEGER;
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_PESSOA_JURIDICA FOREIGN KEY (ID_PESSOA_JURIDICA) REFERENCES PESSOA_JURIDICA(ID);